// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHealth.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyHealth.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811104641_AddTrackingSchema")]
    partial class AddTrackingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyHealth.Api.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Gender")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<int?>("KcalGoal")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("SleepGoalHours")
                        .HasColumnType("double precision");

                    b.Property<int?>("StepsGoal")
                        .HasColumnType("integer");

                    b.Property<double?>("WaterGoalLiters")
                        .HasColumnType("double precision");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.GoogleHealthConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GoogleHealthConnections");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.HealthSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Secondary")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientId")
                        .IsUnique()
                        .HasFilter("\"ClientId\" IS NOT NULL");

                    b.HasIndex("UserId", "Metric", "RecordedAt");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.SleepSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StagesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientId")
                        .IsUnique()
                        .HasFilter("\"ClientId\" IS NOT NULL");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("SleepSessions");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.TagEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "At");

                    b.ToTable("TagEvents");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.DerivedMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactorsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("PeriodEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PeriodStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Unit")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueJson")
                        .HasColumnType("jsonb");

                    b.Property<double?>("ValueNum")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MetricCode", "EffectiveAt")
                        .IsUnique();

                    b.ToTable("DerivedMetrics");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.DeviceInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataOriginAppId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("IntegrationPlatform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("Model")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("SourceDeviceId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IntegrationPlatform", "DataOriginAppId", "SourceDeviceId");

                    b.ToTable("DeviceInstances");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.EventTypeDefinition", b =>
                {
                    b.Property<string>("EventTypeCode")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("Group")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<bool>("Mvp")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RelatedData")
                        .HasColumnType("text");

                    b.Property<string>("TimeBounds")
                        .HasColumnType("text");

                    b.Property<string>("WhenCreated")
                        .HasColumnType("text");

                    b.HasKey("EventTypeCode");

                    b.HasIndex("Mvp");

                    b.ToTable("EventTypeDefinitions");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.MeasurementEventLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkMethod")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("uuid");

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId", "MeasurementType");

                    b.HasIndex("EventId", "MeasurementId", "MeasurementType")
                        .IsUnique();

                    b.ToTable("MeasurementEventLinks");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.MetricDefinition", b =>
                {
                    b.Property<string>("MetricCode")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("Derivation")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Domain")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("Episodes")
                        .HasColumnType("text");

                    b.Property<string>("Grain")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Trigger")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Unit")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("ValueType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("VendorAppleWatch")
                        .HasColumnType("boolean");

                    b.Property<bool>("VendorGarmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("VendorOura")
                        .HasColumnType("boolean");

                    b.Property<bool>("VendorRing")
                        .HasColumnType("boolean");

                    b.Property<bool>("VendorWhoop")
                        .HasColumnType("boolean");

                    b.HasKey("MetricCode");

                    b.ToTable("MetricDefinitions");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("TimezoneOffset")
                        .HasColumnType("interval");

                    b.Property<string>("Unit")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueJson")
                        .HasColumnType("jsonb");

                    b.Property<double?>("ValueNum")
                        .HasColumnType("double precision");

                    b.Property<double?>("ValueSecondary")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DeviceInstanceId");

                    b.HasIndex("MetricCode");

                    b.HasIndex("UserId", "ClientId")
                        .IsUnique()
                        .HasFilter("\"ClientId\" IS NOT NULL");

                    b.HasIndex("UserId", "MetricCode", "StartAt");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.ReferenceRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("MaxNormal")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxWarn")
                        .HasColumnType("double precision");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<double?>("MinNormal")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinWarn")
                        .HasColumnType("double precision");

                    b.Property<string>("Population")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.HasKey("Id");

                    b.HasIndex("MetricCode", "Population")
                        .IsUnique();

                    b.ToTable("ReferenceRanges");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.SourceEventTypeMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Entity")
                        .HasColumnType("text");

                    b.Property<string>("EventTypeCode")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceEventType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Source", "SourceEventType")
                        .IsUnique();

                    b.ToTable("SourceEventTypeMaps");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.TrackedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventTypeCode")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("SourceEventType")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SourceParentRecordId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("TimezoneOffset")
                        .HasColumnType("interval");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceInstanceId");

                    b.HasIndex("EventTypeCode");

                    b.HasIndex("UserId", "ClientId")
                        .IsUnique()
                        .HasFilter("\"ClientId\" IS NOT NULL");

                    b.HasIndex("UserId", "StartAt");

                    b.HasIndex("UserId", "EventTypeCode", "StartAt");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.ValueDictionaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Column")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("Example")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WhenSet")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Column", "Value")
                        .IsUnique();

                    b.ToTable("ValueDictionary");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.VendorMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PeriodEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceDetails")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceDetailsSchemaVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SourceState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Unit")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("ValueNum")
                        .HasColumnType("double precision");

                    b.Property<string>("ValueText")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("VendorMetricCode")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceInstanceId");

                    b.HasIndex("VendorMetricCode");

                    b.HasIndex("UserId", "ClientId")
                        .IsUnique()
                        .HasFilter("\"ClientId\" IS NOT NULL");

                    b.HasIndex("UserId", "VendorMetricCode", "EffectiveAt");

                    b.ToTable("VendorMetrics");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.VendorMetricDefinition", b =>
                {
                    b.Property<string>("VendorMetricCode")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("AppleHealth")
                        .HasColumnType("text");

                    b.Property<bool>("AvailableInMvp")
                        .HasColumnType("boolean");

                    b.Property<string>("ComparisonRule")
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .HasColumnType("text");

                    b.Property<string>("Docs")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<string>("Episodes")
                        .HasColumnType("text");

                    b.Property<string>("FormulaTransparency")
                        .HasColumnType("text");

                    b.Property<string>("Grain")
                        .HasColumnType("text");

                    b.Property<string>("HealthConnect")
                        .HasColumnType("text");

                    b.Property<string>("KnownInputs")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ScaleUnit")
                        .HasColumnType("text");

                    b.Property<string>("UsePolicy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ValueType")
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("VendorApi")
                        .HasColumnType("text");

                    b.Property<string>("VendorField")
                        .HasColumnType("text");

                    b.Property<string>("VendorMetricType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("VendorMetricCode");

                    b.ToTable("VendorMetricDefinitions");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EnergyKcal")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientId")
                        .IsUnique()
                        .HasFilter("\"ClientId\" IS NOT NULL");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.GoogleHealthConnection", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.HealthSample", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.AppUser", "User")
                        .WithMany("Samples")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.RefreshToken", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.SleepSession", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.TagEvent", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.DerivedMetric", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.DeviceInstance", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.MeasurementEventLink", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.Tracking.TrackedEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.Observation", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.Tracking.DeviceInstance", "DeviceInstance")
                        .WithMany()
                        .HasForeignKey("DeviceInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyHealth.Api.Domain.Tracking.MetricDefinition", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyHealth.Api.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceInstance");

                    b.Navigation("Metric");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.TrackedEvent", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.Tracking.DeviceInstance", "DeviceInstance")
                        .WithMany()
                        .HasForeignKey("DeviceInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyHealth.Api.Domain.Tracking.EventTypeDefinition", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyHealth.Api.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceInstance");

                    b.Navigation("EventType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Tracking.VendorMetric", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.Tracking.DeviceInstance", "DeviceInstance")
                        .WithMany()
                        .HasForeignKey("DeviceInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyHealth.Api.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyHealth.Api.Domain.Tracking.VendorMetricDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("VendorMetricCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Definition");

                    b.Navigation("DeviceInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.Workout", b =>
                {
                    b.HasOne("MyHealth.Api.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyHealth.Api.Domain.AppUser", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
