namespace MyHealth.Api.Domain;

/// <summary>
/// Тип показателя здоровья. Имена совпадают с enum HealthMetric во Flutter-клиенте,
/// чтобы сериализация туда-обратно была однозначной.
/// </summary>
public enum MetricType
{
    Steps,
    HeartRate,
    BloodPressure,
    Weight,
    Sleep,
    BloodGlucose,
    BloodOxygen,
    ActiveEnergy,
    Distance,
    Water,
    BodyTemperature,
    RespiratoryRate,
    RestingHeartRate,
    Hrv,
    BodyFat,
    Height,
    DietaryEnergy,
    FlightsClimbed,
    BasalEnergy,
    TotalCalories,
    ExerciseTime,
    StandTime,
    MoveMinutes,
    Mindfulness,
    DistanceCycling,
    DistanceSwimming,
    WalkingHeartRate,
    LeanBodyMass,
    Bmi,
    Waist,
    BodyWater,
    WalkingSpeed,
    Carbs,
    Protein,
    Fat,
    SkinTemperature,
}
